"""
Tasks — assignable cellar work, auto-generated by rules or created by hand.

Deliberate departure from the house append-only pattern (blessed by Nate): a
`Task` is MUTABLE — it gets reassigned, completed, and soft-deleted. To keep the
audit trail intact, every state change is mirrored into an append-only
`TaskEvent`. So the operational object is editable, but the ledger of what
happened to it is still insert-only.

`TaskRule` stores the tunable parameters + on/off switch for an auto-task rule;
the rule *logic* lives in cellar/services/taskrules.py keyed by `key`.
"""
from django.conf import settings
from django.db import models

from .base import AppendOnly


class TaskRule(models.Model):
    """A parameterized auto-task rule (the 'Rules menu'). Logic is in
    services/taskrules.py under RULES[key]; this row holds the knobs."""
    key = models.CharField(max_length=40, unique=True,
                           help_text="matches a rule in services/taskrules.py")
    name = models.CharField(max_length=80)
    description = models.TextField(blank=True)
    enabled = models.BooleanField(default=True)
    params = models.JSONField(default=dict, blank=True,
                              help_text="tunable parameters, e.g. {'interval_days': 60}")

    def __str__(self):
        return self.name


class Task(models.Model):
    """A unit of cellar work. Mutable; state changes are logged to TaskEvent."""
    class Status(models.TextChoices):
        OPEN = "open", "Open"
        COMPLETED = "completed", "Completed"
        DELETED = "deleted", "Deleted"        # soft delete — hidden, retained

    title = models.CharField(max_length=160)
    body = models.TextField(blank=True)
    due_date = models.DateField(null=True, blank=True)
    assignee = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True,
                                 on_delete=models.SET_NULL, related_name="tasks")
    status = models.CharField(max_length=10, choices=Status.choices, default=Status.OPEN)

    # targets — one primary lot, plus optional finer anchors (barrel / rack / addition)
    lot = models.ForeignKey("cellar.Lot", null=True, blank=True,
                            on_delete=models.CASCADE, related_name="tasks")
    container = models.ForeignKey("cellar.Container", null=True, blank=True,
                                  on_delete=models.SET_NULL, related_name="tasks")
    rack = models.ForeignKey("cellar.Rack", null=True, blank=True,
                             on_delete=models.SET_NULL, related_name="tasks")
    addition = models.ForeignKey("cellar.Addition", null=True, blank=True,
                                 on_delete=models.SET_NULL, related_name="tasks")

    # provenance + idempotency
    rule = models.ForeignKey(TaskRule, null=True, blank=True,
                             on_delete=models.SET_NULL, related_name="tasks")
    dedupe_key = models.CharField(max_length=140, null=True, blank=True, unique=True,
                                  help_text="stable key for rule-generated tasks; null for manual")
    # carries a planned addition for the fermentation-nutrition tasks (slice C):
    # completing such a task confirms the dose and books a real Addition.
    payload = models.JSONField(default=dict, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True,
                                   on_delete=models.SET_NULL, related_name="+")
    completed_at = models.DateTimeField(null=True, blank=True)
    completed_by = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True,
                                     on_delete=models.SET_NULL, related_name="+")

    class Meta:
        ordering = ("due_date", "created_at")

    def __str__(self):
        return self.title

    @property
    def target_label(self):
        if self.container_id:
            return self.container.container_id
        if self.rack_id:
            return self.rack.rack_id
        if self.lot_id:
            return self.lot.code
        return "—"

    @property
    def is_overdue(self):
        from django.utils import timezone
        return (self.status == self.Status.OPEN and self.due_date is not None
                and self.due_date < timezone.localdate())


class TaskEvent(AppendOnly):
    """Append-only audit line for a task's lifecycle."""
    class Kind(models.TextChoices):
        CREATED = "created", "Created"
        REASSIGNED = "reassigned", "Reassigned"
        EDITED = "edited", "Edited"
        COMPLETED = "completed", "Completed"
        REOPENED = "reopened", "Reopened"
        DELETED = "deleted", "Deleted"

    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name="events")
    kind = models.CharField(max_length=12, choices=Kind.choices)
    detail = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return f"task {self.task_id} {self.kind} {self.created_at:%Y-%m-%d}"
