# Generated by Django 5.1.15 on 2026-07-10 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0005_tankassignment_emptied_at_vessel_map_col_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='labresult',
            name='sample_id',
            field=models.CharField(blank=True, help_text='outside-lab sample ID (ETS / Lodi); blank for in-house', max_length=60),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='source',
            field=models.CharField(choices=[('in_house', 'In-house'), ('ets', 'ETS'), ('lodi', 'Lodi Wine Labs')], default='ets', max_length=10),
        ),
        migrations.CreateModel(
            name='LotSectionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('overview', 'Overview'), ('additions', 'Additions'), ('labs', 'Labs'), ('movement', 'Movement'), ('composition', 'Composition'), ('oak', 'Oak')], max_length=16)),
                ('body', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_notes', to='cellar.lot')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('lot', 'section')},
            },
        ),
    ]
