# Generated by Django 5.1.15 on 2026-07-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0010_labsamplealias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('receiving', 'Receiving'), ('processing', 'Processing'), ('cold_soak', 'Cold soak'), ('fermenting', 'Fermenting'), ('pressed', 'Pressed'), ('settling', 'Settling'), ('done_primary', 'Primary complete'), ('bottled', 'Bottled')], default='receiving', max_length=14),
        ),
        migrations.AlterField(
            model_name='lotdesignation',
            name='kind',
            field=models.CharField(choices=[('standard', 'Standard'), ('blend', 'Blend'), ('coferment', 'Co-ferment'), ('split', 'Split'), ('bottling', 'Bottling parcel')], max_length=12),
        ),
        migrations.AlterField(
            model_name='lotlineage',
            name='relationship_type',
            field=models.CharField(choices=[('split_saignee', 'Split — saignée'), ('split_drainoff', 'Split — drain-off'), ('whole_blend', 'Whole-lot blend'), ('partial_blend_contribution', 'Partial blend contribution'), ('topping_contribution', 'Topping contribution'), ('bottling_split', 'Bottling parcel split')], max_length=32),
        ),
    ]
