# Generated by Django 5.1.15 on 2026-07-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='additive',
            name='default_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='numeric default rate; its unit is rate_unit', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='additive',
            name='default_target_ppm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='ppm_target additives, e.g. SO₂ 40 at crush', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='additive',
            name='dose_mode',
            field=models.CharField(choices=[('per_volume', 'Rate per volume'), ('per_ton', 'Rate per ton of fruit'), ('ppm_target', 'SO₂ to target ppm'), ('bench', 'Bench trial (no default)')], default='per_volume', max_length=12),
        ),
        migrations.AddField(
            model_name='additive',
            name='rate_unit',
            field=models.CharField(blank=True, help_text='lb/1000gal · g/hL · L/1000gal · mL/hL · mL/ton', max_length=20),
        ),
        migrations.AddField(
            model_name='additive',
            name='so2_fraction',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='ppm_target: SO₂ mass fraction of the product (KMBS 0.5764)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='additive',
            name='category',
            field=models.CharField(choices=[('so2', 'SO₂ / KMBS'), ('acid', 'Acid'), ('tannin', 'Tannin'), ('enzyme', 'Enzyme'), ('nutrient', 'Nutrient'), ('yeast', 'Yeast'), ('fining', 'Fining agent'), ('other', 'Other')], max_length=12),
        ),
        migrations.AlterField(
            model_name='additive',
            name='unit',
            field=models.CharField(help_text='costing/inventory unit, e.g. g, kg, lb, mL, L', max_length=20),
        ),
    ]
