# Generated by Django 5.1.15 on 2026-07-08 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0002_additive_default_rate_additive_default_target_ppm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destemmingevent',
            name='processing_path',
            field=models.CharField(choices=[('A', 'A · White (destemmed)'), ('B', 'B · Rosé (destemmed)'), ('C', 'C · Rosé (direct press)'), ('D', 'D · Red (destemmed)'), ('E', 'E · Red (whole cluster)'), ('F', 'F · White (whole cluster)')], help_text='processing path per Destemming SOP', max_length=1),
        ),
    ]
