# Generated by Django 5.1.15 on 2026-07-10 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0003_alter_destemmingevent_processing_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='destemmingevent',
            name='foot_tread_pct',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='% of the lot foot-tread, by bin count (3 of 6 bins → 50)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='weightag',
            name='mog_severity',
            field=models.CharField(choices=[('none', 'None'), ('light', 'Light'), ('moderate', 'Moderate'), ('heavy', 'Heavy')], default='none', help_text='material other than grapes', max_length=8),
        ),
        migrations.AddField(
            model_name='weightag',
            name='notes',
            field=models.TextField(blank=True, help_text='free-form intake notes for this delivery'),
        ),
        migrations.AddField(
            model_name='weightag',
            name='rot_severity',
            field=models.CharField(choices=[('none', 'None'), ('light', 'Light'), ('moderate', 'Moderate'), ('heavy', 'Heavy')], default='none', max_length=8),
        ),
        migrations.AddField(
            model_name='weightag',
            name='rot_type',
            field=models.CharField(blank=True, help_text='e.g. botrytis, sour', max_length=40),
        ),
        migrations.AddField(
            model_name='weightagbin',
            name='assigned_lot',
            field=models.ForeignKey(blank=True, help_text='the lot this bin was crushed into, if assigned', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bins', to='cellar.lot'),
        ),
    ]
