# Generated by Django 5.1.15 on 2026-07-10 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0004_destemmingevent_foot_tread_pct_weightag_mog_severity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tankassignment',
            name='emptied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vessel',
            name='map_col',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vessel',
            name='map_row',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vessel',
            name='room',
            field=models.CharField(blank=True, choices=[('old_tank', 'Old Tank Room'), ('new_tank', 'New Tank Room'), ('new_barrel', 'New Barrel Room')], max_length=12),
        ),
    ]
