# Generated by Django 5.1.15 on 2026-07-10 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0006_labresult_sample_id_alter_labresult_source_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labanalyte',
            options={'ordering': ('sort_order', 'name')},
        ),
        migrations.AddField(
            model_name='labanalyte',
            name='slug',
            field=models.SlugField(blank=True, max_length=40, unique=True),
        ),
        migrations.AddField(
            model_name='labanalyte',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=100, help_text='panel display order — lower shows first'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='panel',
            field=models.CharField(choices=[('juice', 'Juice panel'), ('chemistry', 'Chemistry panel'), ('heat_stability', 'Heat stability'), ('smoke', 'Smoke'), ('other', 'Other')], default='other', help_text='panel classification, set from the analytes present', max_length=14),
        ),
        migrations.AddField(
            model_name='labresultvalue',
            name='display',
            field=models.CharField(blank=True, help_text='how the reading is shown (ND / Dry / FAIL / the number)', max_length=40),
        ),
        migrations.AddField(
            model_name='labresultvalue',
            name='flag',
            field=models.CharField(blank=True, choices=[('', '—'), ('ND', 'ND (not detected)'), ('Dry', 'Dry'), ('Pass', 'Pass (heat-stable)'), ('FAIL', 'FAIL (heat-unstable)'), ('note', 'Note')], default='', max_length=8),
        ),
        migrations.AddField(
            model_name='labresultvalue',
            name='qualifier',
            field=models.CharField(choices=[('=', '='), ('<', '< (below detection / threshold)'), ('>', '> (above threshold)')], default='=', max_length=1),
        ),
        migrations.AddField(
            model_name='labresultvalue',
            name='raw_result',
            field=models.CharField(blank=True, help_text='untouched source string, for audit', max_length=200),
        ),
        migrations.AlterField(
            model_name='labresultvalue',
            name='value',
            field=models.DecimalField(decimal_places=3, help_text='numeric reading used by calcs; 0 for ND / Dry', max_digits=10),
        ),
        migrations.CreateModel(
            name='LabAnalyteSynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_name', models.CharField(help_text="exact 'Analysis Name' string as ETS prints it", max_length=120, unique=True)),
                ('analyte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='cellar.labanalyte')),
            ],
        ),
    ]
