# Generated by Django 5.1.15 on 2026-07-11 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0009_seed_reference_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabSampleAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text="exact 'Sample Description' as the lab prints it", max_length=120, unique=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_aliases', to='cellar.lot')),
            ],
            options={
                'verbose_name_plural': 'lab sample aliases',
            },
        ),
    ]
