# Generated by Django 5.1.15 on 2026-07-12 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0011_alter_lot_status_alter_lotdesignation_kind_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FruitPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vintage_year', models.PositiveSmallIntegerField()),
                ('price_per_ton', models.DecimalField(decimal_places=2, max_digits=9)),
                ('notes', models.CharField(blank=True, max_length=120)),
                ('block', models.ForeignKey(blank=True, help_text='blank = the varietal price for that vintage', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='cellar.block')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='cellar.variety')),
            ],
            options={
                'ordering': ['-vintage_year', 'variety__name'],
                'unique_together': {('vintage_year', 'variety', 'block')},
            },
        ),
    ]
