# Generated by Django 5.1.15 on 2026-07-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0013_seed_bottling_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='fortificationevent',
            name='base_tax_class',
            field=models.CharField(choices=[('a', 'Not over 16% (col a)'), ('b', 'Over 16–21% (col b)'), ('c', 'Over 21–24% (col c)')], default='a', help_text='the class the base wine was in BEFORE this event. Initial → (a): fresh base wine is under 16%. Adjustment → whatever it already was.', max_length=1),
        ),
        migrations.AddField(
            model_name='fortificationevent',
            name='kind',
            field=models.CharField(choices=[('initial', 'Initial (fortified on skins)'), ('adjustment', 'Alcohol adjustment (already in bond)')], default='initial', max_length=12),
        ),
    ]
