# Generated by Django 5.1.15 on 2026-07-12 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0016_remove_pressing_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktobond',
            name='gauge_source',
            field=models.CharField(choices=[('tank_gauge', 'Tank gauge (pressure sensor)'), ('barrel_fill', 'Barrel fill (sum of actual fills)'), ('stated', 'Stated')], default='stated', help_text='how the produced volume was determined', max_length=12),
        ),
        migrations.AddField(
            model_name='booktobond',
            name='volume',
            field=models.ForeignKey(blank=True, help_text='the authoritative gauge this booking was struck from', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cellar.volumemeasurement'),
        ),
        migrations.AddField(
            model_name='pressingevent',
            name='volume',
            field=models.ForeignKey(blank=True, help_text='the post-press gauge, if any', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cellar.volumemeasurement'),
        ),
        migrations.AlterField(
            model_name='booktobond',
            name='tax_class',
            field=models.CharField(choices=[('a', 'Not over 16% (col a)'), ('b', 'Over 16–21% (col b)'), ('c', 'Over 21–24% (col c)')], default='a', help_text='col a (≤16%) at booking — INCLUDING Port base wine. Fortification moves it to col b, not this row.', max_length=1),
        ),
    ]
