# Generated by Django 5.1.15 on 2026-07-14 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0020_dailyplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('bw_number', models.CharField(blank=True, help_text='e.g. BW-CA-1234 — required for in-bond (not-yet-taxpaid) transfers', max_length=30)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='additive',
            name='crush_addition',
            field=models.BooleanField(default=False, help_text="Show in the crush/intake additions picker (Section 5). Everything else stays off that list but is still usable from a lot's regular Additions tab."),
        ),
        migrations.AddField(
            model_name='vessel',
            name='glycol_setpoint_f',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Target glycol setpoint (°F) — informational; the human still sets the dial.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bondtransfer',
            name='destination',
            field=models.ForeignKey(blank=True, help_text='reference-table pick; counterparty stays the free-text display', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cellar.externaldestination'),
        ),
        migrations.AddField(
            model_name='bulktaxpaidremoval',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cellar.externaldestination'),
        ),
    ]
