# Generated by Django 5.1.15 on 2026-07-14 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0022_seed_crush_additives_and_in_house_analytes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MustSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voided_at', models.DateTimeField(blank=True, help_text='void a wrong entry — kept for audit, excluded from reports', null=True)),
                ('notes', models.TextField(blank=True)),
                ('gallons', models.DecimalField(decimal_places=1, max_digits=10)),
                ('sold_at', models.DateField()),
                ('price_per_gallon', models.DecimalField(blank=True, decimal_places=2, help_text='optional — accounting reference only', max_digits=7, null=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cellar.externaldestination')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='must_sales', to='cellar.lot')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cellar.mustsale')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
