# Generated by Django 5.1.15 on 2026-07-17 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0024_pct_volume_dose_mode_and_water_additive'),
    ]

    operations = [
        migrations.AddField(
            model_name='agingplacement',
            name='legacy_lot_code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='container',
            name='pool',
            field=models.CharField(blank=True, choices=[('table', 'Table wine'), ('port', 'Port')], max_length=8),
        ),
        migrations.AddField(
            model_name='rack',
            name='size_class',
            field=models.CharField(choices=[('standard', 'Standard (55/60/70)'), ('large', 'Large (130)')], default='standard', help_text='which barrel size this rack holds', max_length=10),
        ),
        migrations.AlterField(
            model_name='agingplacement',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='cellar.lot'),
        ),
    ]
