# Generated by Django 5.1.15 on 2026-07-18 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0025_barrel_pool_sizeclass_legacy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LotCostAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voided_at', models.DateTimeField(blank=True, help_text='void a wrong entry — kept for audit, excluded from reports', null=True)),
                ('notes', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('oak', 'Oak / barrel'), ('overhead', 'Cellar overhead'), ('labor', 'Labor'), ('additives', 'Additives (not itemized)'), ('other', 'Other')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, help_text='signed dollars; negative to credit a lot', max_digits=12)),
                ('incurred_at', models.DateField()),
                ('basis', models.CharField(choices=[('entered', 'Entered per lot'), ('allocated', 'Allocated from a pool')], default='entered', help_text='entered per lot, or allocated from a pool', max_length=10)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_adjustments', to='cellar.lot')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cellar.lotcostadjustment')),
            ],
            options={
                'ordering': ('incurred_at', 'id'),
            },
        ),
    ]
