# Generated by Django 5.1.15 on 2026-07-19 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0026_lotcostadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotlineage',
            name='cost_per_gal_snapshot',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="parent's $/gal at the moment of transfer; null = fall back to live computation", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lotlineage',
            name='occurred_at',
            field=models.DateField(blank=True, help_text='business date the wine moved (not the keying date)', null=True),
        ),
    ]
