# Generated by Django 5.1.15 on 2026-07-19 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _untrack_volume_additives(apps, schema_editor):
    """Water (dose_mode=pct_volume) is dosed but never purchased as consumable
    stock, so it must not draw an ISSUE. Bench trials likewise have no default
    quantity to draw. Everything else stays tracked."""
    Additive = apps.get_model("cellar", "Additive")
    Additive.objects.filter(dose_mode__in=("pct_volume", "bench")).update(track_stock=False)


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0027_lotlineage_cost_basis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='addition',
            name='unit_cost_snapshot',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='additive',
            name='track_stock',
            field=models.BooleanField(default=True, help_text='draw this from consumable inventory when added'),
        ),
        migrations.AddField(
            model_name='bottlingdrygooduse',
            name='unit_cost_snapshot',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='WAC at the bottling run, frozen', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='additive',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="seed/fallback cost per unit; the live figure is the stock ledger's weighted average once receipts exist", max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='PhysicalCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voided_at', models.DateTimeField(blank=True, help_text='void a wrong entry — kept for audit, excluded from reports', null=True)),
                ('notes', models.TextField(blank=True)),
                ('counted_on', models.DateField()),
                ('label', models.CharField(blank=True, help_text="e.g. 'FY25 year-end', 'post-bottling spot check'", max_length=120)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cellar.physicalcount')),
            ],
            options={
                'ordering': ('-counted_on', '-id'),
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voided_at', models.DateTimeField(blank=True, help_text='void a wrong entry — kept for audit, excluded from reports', null=True)),
                ('notes', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('receipt', 'Receipt'), ('issue', 'Issued to production'), ('count_adj', 'Count adjustment'), ('write_down', 'Write-down / disposal')], max_length=12)),
                ('occurred_at', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=4, help_text="signed, in the item's stock unit", max_digits=14)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=6, help_text='receipt: landed ÷ qty. issue: WAC at issue.', max_digits=12, null=True)),
                ('extended_cost', models.DecimalField(decimal_places=2, default=0, help_text='signed dollars = quantity × unit_cost', max_digits=14)),
                ('supplier', models.CharField(blank=True, max_length=120)),
                ('reference', models.CharField(blank=True, help_text='PO / invoice no.', max_length=60)),
                ('goods_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('freight_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pack_count', models.DecimalField(blank=True, decimal_places=2, help_text='how many packs, e.g. 4 bags', max_digits=10, null=True)),
                ('pack_size', models.DecimalField(blank=True, decimal_places=4, help_text='size of one pack, e.g. 1 (kg)', max_digits=12, null=True)),
                ('pack_unit', models.CharField(blank=True, help_text="purchase unit, e.g. kg — converted to the item's stock unit", max_length=20)),
                ('reason', models.CharField(blank=True, help_text='write-down reason: expired, spilled, damaged…', max_length=160)),
                ('addition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_txns', to='cellar.addition')),
                ('additive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_txns', to='cellar.additive')),
                ('count', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='cellar.physicalcount')),
                ('dry_good', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_txns', to='cellar.drygood')),
                ('dry_good_use', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_txns', to='cellar.bottlingdrygooduse')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_txns', to='cellar.material')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cellar.stocktransaction')),
            ],
            options={
                'ordering': ('occurred_at', 'id'),
                'indexes': [models.Index(fields=['additive', 'occurred_at'], name='cellar_stoc_additiv_2f236d_idx'), models.Index(fields=['dry_good', 'occurred_at'], name='cellar_stoc_dry_goo_741118_idx'), models.Index(fields=['material', 'occurred_at'], name='cellar_stoc_materia_93c57a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('additive__isnull', False), ('dry_good__isnull', True), ('material__isnull', True)), models.Q(('additive__isnull', True), ('dry_good__isnull', False), ('material__isnull', True)), models.Q(('additive__isnull', True), ('dry_good__isnull', True), ('material__isnull', False)), _connector='OR'), name='stocktxn_exactly_one_item')],
            },
        ),
        migrations.RunPython(_untrack_volume_additives, _noop),
    ]
