# Generated by Django 5.1.15 on 2026-07-19 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0028_stock_ledger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('posted', 'Posted to QBO')], default='open', max_length=8)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('qbo_journal_entry_id', models.CharField(blank=True, help_text='set when the summary JE lands in QBO', max_length=60)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-year', '-month'),
                'constraints': [models.UniqueConstraint(fields=('year', 'month'), name='costperiod_unique_year_month')],
            },
        ),
        migrations.CreateModel(
            name='CostEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voided_at', models.DateTimeField(blank=True, help_text='void a wrong entry — kept for audit, excluded from reports', null=True)),
                ('notes', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('fruit', 'Fruit'), ('additive', 'Additives'), ('spirit', 'Spirit (HPGS)'), ('oak', 'Oak / barrel depreciation'), ('packaging', 'Packaging / dry goods'), ('labor', 'Labor'), ('overhead', 'Cellar overhead'), ('adjustment', 'Manual adjustment'), ('transfer_in', 'Cost transferred in'), ('transfer_out', 'Cost transferred out'), ('shrinkage', 'Inventory shrinkage'), ('abnormal_loss', 'Abnormal loss'), ('idle_capacity', 'Idle capacity')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, help_text='signed dollars', max_digits=14)),
                ('occurred_at', models.DateField(help_text='business date of the underlying event')),
                ('source_kind', models.CharField(blank=True, max_length=32)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('deferred_note', models.CharField(blank=True, help_text="set when the event's own month was already closed and the cost was posted forward instead — mandatory, so a shifted cost is never silent", max_length=200)),
                ('lot', models.ForeignKey(blank=True, help_text='null for period expense with no wine to attach to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_entries', to='cellar.lot')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cellar.costentry')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='cellar.costperiod')),
            ],
            options={
                'ordering': ('occurred_at', 'id'),
                'indexes': [models.Index(fields=['lot', 'category'], name='cellar_cost_lot_id_981674_idx'), models.Index(fields=['period', 'category'], name='cellar_cost_period__b4645d_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source_id__isnull', False), ('voided_at__isnull', True)), fields=('source_kind', 'source_id', 'category'), name='costentry_one_live_posting_per_source')],
            },
        ),
    ]
