# Generated by Django 5.1.15 on 2026-07-19 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0029_cost_ledger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OverheadPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('category', models.CharField(default='overhead', help_text="CostEntry category this pool posts as — 'labor' or 'overhead'", max_length=16)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.AddField(
            model_name='volumeloss',
            name='is_abnormal',
            field=models.BooleanField(default=False, help_text='expense this loss instead of capitalizing it into the remaining wine'),
        ),
        migrations.CreateModel(
            name='OverheadPoolPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voided_at', models.DateTimeField(blank=True, help_text='void a wrong entry — kept for audit, excluded from reports', null=True)),
                ('notes', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='total dollars in this pool for this month', max_digits=12)),
                ('allocated_at', models.DateTimeField(blank=True, null=True)),
                ('absorbed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('idle_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('absorbing_gallons', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pool_amounts', to='cellar.costperiod')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periods', to='cellar.overheadpool')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cellar.overheadpoolperiod')),
            ],
            options={
                'ordering': ('period', 'pool'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('voided_at__isnull', True)), fields=('pool', 'period'), name='overheadpoolperiod_one_live_per_pool_month')],
            },
        ),
    ]
