# Generated by Django 5.1.15 on 2026-07-21 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0030_overhead_pools'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fruitprice',
            name='basis',
            field=models.CharField(choices=[('arms_length_sale', "Arm's-length sale (same vintage)"), ('contract', 'Third-party purchase contract'), ('district_average', 'Grape Crush Report — same vintage'), ('prior_year_district', 'Grape Crush Report — prior vintage'), ('farming_cost', 'Actual farming cost'), ('negotiated', 'Negotiated / other')], default='contract', help_text='how this price was arrived at', max_length=20),
        ),
        migrations.AddField(
            model_name='fruitprice',
            name='is_provisional',
            field=models.BooleanField(default=False, help_text='priced on data that will be superseded; owed a true-up when the final figure publishes'),
        ),
        migrations.AddField(
            model_name='fruitprice',
            name='source_ref',
            field=models.CharField(blank=True, help_text="the document behind it — contract or invoice no., or 'Grape Crush Report 2025 Final, District 11, Zinfandel'", max_length=160),
        ),
        migrations.CreateModel(
            name='FruitPriceRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voided_at', models.DateTimeField(blank=True, help_text='void a wrong entry — kept for audit, excluded from reports', null=True)),
                ('notes', models.TextField(blank=True)),
                ('final_price_per_ton', models.DecimalField(decimal_places=2, max_digits=9)),
                ('basis', models.CharField(choices=[('arms_length_sale', "Arm's-length sale (same vintage)"), ('contract', 'Third-party purchase contract'), ('district_average', 'Grape Crush Report — same vintage'), ('prior_year_district', 'Grape Crush Report — prior vintage'), ('farming_cost', 'Actual farming cost'), ('negotiated', 'Negotiated / other')], default='district_average', help_text='how the FINAL price was arrived at', max_length=20)),
                ('source_ref', models.CharField(blank=True, help_text="the published figure this came from — e.g. 'Grape Crush Report 2026 Final, District 11, Zinfandel'", max_length=160)),
                ('effective_on', models.DateField(help_text='business date the true-up is booked — normally the date the final report published, NOT the delivery date')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='cellar.fruitprice')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cellar.fruitpricerevision')),
            ],
            options={
                'ordering': ('-effective_on', '-id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('voided_at__isnull', True)), fields=('price',), name='fruitpricerevision_one_live_per_price')],
            },
        ),
    ]
